
package ua.artcode.week9.soap.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UserAlreadyExistsException", targetNamespace = "http://endpoint.soap.week9.artcode.ua/")
public class UserAlreadyExistsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UserAlreadyExistsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UserAlreadyExistsException_Exception(String message, UserAlreadyExistsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UserAlreadyExistsException_Exception(String message, UserAlreadyExistsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ua.artcode.week9.soap.endpoint.UserAlreadyExistsException
     */
    public UserAlreadyExistsException getFaultInfo() {
        return faultInfo;
    }

}
